name: Test Collector
description: Uploads your JSON or JUnit files to Buildkite Test Analytics
author: https://github.com/buildkite
requirements:
  - docker
  - curl
configuration:
  properties:
    hook:
      type: string
      default: pre-exit
      values: ["pre-exit", "post-artifact", "post-command"]
    files:
      type: string
    format:
      enum:
        - json
        - junit
    api-token-env-name:
      type: string
    debug:
      type: boolean
    timeout:
      type: integer
  required:
    - files
    - format
  additionalProperties: false
